# Generated by Django 2.2.9 on 2020-01-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20200112_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='body',
            field=models.CharField(max_length=255),
        ),
    ]
