# Generated by Django 2.2.9 on 2020-01-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20200112_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=models.SlugField(default='python-data-types', unique=True),
            preserve_default=False,
        ),
    ]
