# Generated by Django 2.2.9 on 2020-01-13 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='choices',
            field=models.ManyToManyField(blank=True, to='quiz.Choice'),
        ),
    ]
