# Generated by Django 2.2.9 on 2020-01-14 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20200113_0355'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
